robot_radius: 0.271
footprint_padding: 0.01

robot_base_frame: base_link
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 2.0
raytrace_range: 3.0

#layer definitions
static:
  map_topic: map
  subscribe_to_updates: true

obstacles_camera:
  observation_sources: point_cloud
  point_cloud: { data_type: PointCloud2, clearing: true, marking: true, topic: cutoff/output, inf_is_valid: true }

inflation:
  inflation_radius: 0.5