global_frame: map
update_frequency: 1.0
publish_frequency: 3.0
static_map: true
rolling_window: false
track_unknown_space: true

plugins:
  - { name: static_global,                  type: "costmap_2d::StaticLayer" }
  - { name: inflation,               type: "costmap_2d::InflationLayer" }