global_frame: odom
rolling_window: true
inflation_radius: 0.5
width: 3
height: 3

plugins:
  - { name: obstacles_camera,           type: "costmap_2d::ObstacleLayer" }
  - { name: inflation,                 type: "costmap_2d::InflationLayer" }