base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

planner_frequency: 2
planner_patience: 10.0
planner_max_retries: 10

controller_frequency: 5.0
controller_patience: 3.0
controller_max_retries: 10

recovery_patience: 10.0
recovery_behaviour_enabled: true

oscillation_timeout: 10.0
oscillation_distance: 0.2
