rm_fsm:
  robot_type: "hero"
  control_param:
    accel_x: 10.0
    accel_y: 10.0
    accel_angular: 10.0
    brake_multiple: 2
    shoot_hz: 5
    shoot_speed: 10
    gimbal_error_limit: 0.1745
    rc_param:
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 6.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
    pc_param:
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 6.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
  power_limit:
    danger_surplus: 20.0
    roll_back_buffer: 55.0
    coeff: 0.3
    multiple: 15.0
  shooter_heat_limit:
    safe_hz: 2