rm_fsm:
  robot_type: "hero"
  control_param:
    rc_param:
      accel_x: 10.0
      accel_y: 10.0
      accel_angular: 10.0
      brake_multiple: 2
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 6.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
      shoot_hz: 5
    pc_param:
      accel_x: 10.0
      accel_y: 10.0
      accel_angular: 10.0
      brake_multiple: 2
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 6.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
      shoot_hz: 5
  power_limit:
    danger_surplus_: 20.0
    roll_back_buffer_: 55.0
    coeff: 0.3
    multiple: 15.0