rm_fsm:
  robot_type: "hero"
  control_param:
    accel_x: 8.0
    accel_y: 8.0
    accel_angular: 8.0
    brake_multiple: 2
    expect_shoot_hz: 4
    safe_shoot_hz: 1
    safe_shoot_speed: 10
    gimbal_error_limit: 0.17
    safety_power: 50
    have_power_manager: false
    rc_param:
      coefficient_x: 5
      coefficient_y: 5
      coefficient_angular: 5.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
    pc_param:
      coefficient_x: 5
      coefficient_y: 5
      coefficient_angular: 3.0
      coefficient_yaw: 750.0
      coefficient_pitch: 750.0
      normal_critical_speed: 1
      burst_critical_speed: 2
      normal_angular: 3.0
      burst_angular: 5.0
      spin_sin_amplitude: 3.0
      spin_sin_frequency: 6.28
    power_limit:
      safety_power: 50
      have_power_manager: false
  target_cost_function:
    k_f: 0.18
    k_hp: 0.0
    cost_clean_time: 2.5
    track_msg_timeout: 1.0

