rm_fsm:
  robot_type: "hero"
  control_param:
    accel_x: 10.0
    accel_y: 10.0
    accel_angular: 6.0
    brake_multiple: 2
    expect_shoot_hz: 4
    safe_shoot_hz: 1
    safe_shoot_speed: 10
    gimbal_error_limit: 0.17
    rc_param:
      coefficient_x: 4
      coefficient_y: 4
      coefficient_angular: 5.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
    pc_param:
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 1.0
      coefficient_yaw: 750.0
      coefficient_pitch: 750.0
      normal_critical_speed: 1
      burst_critical_speed: 2
      normal_angular: 1
      burst_angular: 2
      spin_sin_amplitude: 3.0
      spin_sin_frequency: 6.28
  power_limit:
    safety_power: 50
    have_power_manager: false


