rm_fsm:
  robot_type: "hero"
  control_param:
    accel_x: 10.0
    accel_y: 10.0
    accel_angular: 6.0
    brake_multiple: 2
    expect_shoot_hz: 4
    safe_shoot_hz: 1
    safe_shoot_speed: 10
    gimbal_error_limit: 0.17
    rc_param:
      coefficient_x: 4
      coefficient_y: 4
      coefficient_angular: 5.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
    pc_param:
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 1.0
      coefficient_yaw: 750.0
      coefficient_pitch: 750.0
      normal_critical_speed: 1
      burst_critical_speed: 2
      normal_angular: 1
      burst_angular: 2
      spin_sin_amplitude: 3.0
      spin_sin_frequency: 6.28
  power_limit:
    ff: 0
    safety_current: 7.5
    wheel_radius: 0.07625
    use_power_manager: false
    pid_buffer: { p: 0.021, i: 0.005, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true }
    pid_buffer_power_manager: { p: 10.0, i: 0.1, d: 0.05, i_max: 0.0, i_min: 0.0, antiwindup: true }


