rm_fsm:
  robot_type: "sentry"
  chassis:
    topic: "/cmd_chassis"
    accel_x: 2.0
    accel_y: 10.0
    accel_z: 20.0
    safety_power: 30.0
  vel:
    topic: "/cmd_vel"
    max_linear_x: 3.0
    max_linear_y: 4.0
    max_angular_z: 5.0
  gimbal:
    topic: "/cmd_gimbal"
    max_yaw_vel: 2.0
    max_pitch_vel: 2.0
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "/cmd_shoot"
    gimbal_error_limit: 0.2
    heat_limit:
      expect_shoot_frequency: 10
      safe_shoot_frequency: 10
      heat_coeff: 1.5
      type: "ID1_17MM"
  auto:
    move_distance: 1.45
    collision_distance: 0.3
    collision: false
    calibrate:
      scale_x: 0.2
    move:
      scale_x: 1.6
      scale_pitch: 0.8
      scale_yaw: 2.5

    chassis_speed: 1.6
    chassis_accel: 1.0
    pitch_speed: 0.8
    yaw_speed: 2.5
    start: 0.0
    end: 2.0
    #    collision_distance: 0.3
    calibration_speed: 0.2
    column: true
  controller_manager:
    information_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    movement_controllers:
      - controllers/chassis_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
