rm_fsm:
  robot_type: "sentry"
  control_param:
    accel_x: 5.0
    accel_y: 5.0
    accel_angular: 10.0
    brake_multiple: 2
    expect_shoot_hz: 10
    safe_shoot_hz: 3
    safe_shoot_speed: 10
    gimbal_error_limit: 1
    rc_param:
      coefficient_x: 1.0
      coefficient_y: 1.0
      coefficient_angular: 6.0
      coefficient_yaw: 1.0
      coefficient_pitch: 1.0
  power_limit:
    danger_surplus: 20.0
    roll_back_buffer: 55.0
    coeff: 0.3
    multiple: 15.0
    safety_current: 6.0
    use_power_manager: false
    default_power_limit: true
  auto_move:
    chassis_speed: 1.3
    chassis_accel: 1.0
    pitch_speed: 0.5
    yaw_speed: 3.14
    start: 0.3
    end: 1.00
    calibration_speed: 0.15

