rm_fsm:
  robot_type: "sentry"
  chassis:
    topic: "/controllers/chassis_controller/command"
    accel_x: 9999.0
    accel_y: 0.0
    accel_z: 0.0
    safety_power: 30.0
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 30
    burst_power: 200
  vel:
    topic: "/cmd_vel"
    max_linear_x: 3.0
    max_linear_y: 0.0
    max_angular_z: 0.0
  auto:
    auto_linear_x: 1.0
    move_distance: 2.7
    stop_distance: 0.5
    collision_effort: 0.8
  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/tf_radar_controller