rm_fsm:
  robot_type: "sentry"
  chassis:
    topic: "/controllers/chassis_controller/command"
    accel_x: 2.0
    accel_y: 10.0
    accel_z: 20.0
    safety_power: 30.0
    capacitor_threshold: 0.1
    charge_power: 20
    extra_power: 30
    burst_power: 200
  vel:
    topic: "/cmd_vel"
    max_linear_x: 3.0
    max_linear_y: 4.0
    max_angular_z: 5.0
  upper_gimbal:
    topic: "/controllers/upper_gimbal_controller/command"
    max_yaw_vel: 4.0
    max_pitch_vel: 2.0
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  lower_gimbal:
    topic: "/controllers/lower_gimbal_controller/command"
    max_yaw_vel: 4.0
    max_pitch_vel: 2.0
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  upper_shooter:
    topic: "/controllers/upper_shooter_controller/command"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency_1: 5
      expect_shoot_frequency_2: 8
      expect_shoot_frequency_3: 12
      burst_shoot_frequency: 20
      safe_shoot_frequency: 5
      heat_coeff: 8.0
      type: "ID1_17MM"
  lower_shooter:
    topic: "/controllers/lower_shooter_controller/command"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency_1: 5
      expect_shoot_frequency_2: 8
      expect_shoot_frequency_3: 12
      burst_shoot_frequency: 20
      safe_shoot_frequency: 5
      heat_coeff: 8.0
      type: "ID1_17MM"
  auto:
    move_distance: 1.45
    stop_distance: 0.2
    collision_effort: 0.062
    calibrate:
      scale_x: 0.2
    attack:
      scale_x: 0.2
      upper:
        pitch:
          scale: 0.3
          min: 0.45
          max: 0.75
        yaw:
          scale: 0.3
          min: -2.70
          max: -0.40
      lower:
        pitch:
          scale: 0.3
          min: 0.45
          max: 0.75
        yaw:
          scale: 0.3
          min: -2.70
          max: -0.40
  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/upper_gimbal_controller
      - controllers/lower_gimbal_controller
      - controllers/upper_shooter_controller
      - controllers/lower_shooter_controller
    calibration_controllers:
      - controllers/upper_trigger_calibration_controller
      - controllers/upper_yaw_calibration_controller
      - controllers/upper_pitch_calibration_controller
      - controllers/lower_trigger_calibration_controller
      - controllers/lower_yaw_calibration_controller
      - controllers/lower_pitch_calibration_controller

  power_on_calibration:
    - start_controller: controllers/upper_trigger_calibration_controller
      stop_controller: controllers/upper_shooter_controller
      service_name: /controllers/upper_trigger_calibration_controller/is_calibrated
    - start_controller: controllers/upper_yaw_calibration_controller
      stop_controller: controllers/upper_gimbal_controller
      service_name: /controllers/upper_yaw_calibration_controller/is_calibrated
    - start_controller: controllers/upper_pitch_calibration_controller
      stop_controller: controllers/upper_gimbal_controller
      service_name: /controllers/upper_pitch_calibration_controller/is_calibrated
    - start_controller: controllers/lower_trigger_calibration_controller
      stop_controller: controllers/lower_shooter_controller
      service_name: /controllers/lower_trigger_calibration_controller/is_calibrated
    - start_controller: controllers/lower_yaw_calibration_controller
      stop_controller: controllers/lower_gimbal_controller
      service_name: /controllers/lower_yaw_calibration_controller/is_calibrated
    - start_controller: controllers/lower_pitch_calibration_controller
      stop_controller: controllers/lower_gimbal_controller
      service_name: /controllers/lower_pitch_calibration_controller/is_calibrated