rm_fsm:
  robot_type: "sentry"
  chassis:
    topic: "/cmd_chassis"
    accel_x: 2.0
    accel_y: 10.0
    accel_z: 20.0
    safety_power: 30.0
  vel:
    topic: "/cmd_vel"
    max_linear_x: 3.0
    max_linear_y: 4.0
    max_angular_z: 5.0
  gimbal:
    topic: "/cmd_gimbal"
    max_yaw_vel: 4.0
    max_pitch_vel: 4.0
    track_timeout: 0.5
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "/cmd_shoot"
    gimbal_error_limit: 0.05
    heat_limit:
      expect_shoot_frequency: 30
      safe_shoot_frequency: 10
      heat_coeff: 1.5
      type: "ID1_17MM"
  auto:
    move_distance: 1.45
    stop_distance: 0.2
    collision_distance: 0.3
    collision_effort: 0.062
    collision_flag: true
    calibrate:
      scale_x: 0.2
    move:
      scale_x: 0.2
      scale_pitch: 0.8
      scale_yaw: 1.0
  controllers_list:
    - controllers/robot_state_controller
    - controllers/joint_state_controller
    - controllers/chassis_controller
    - controllers/gimbal_controller
    - controllers/shooter_controller
    - controllers/trigger_calibration_controller
  state_controllers_switch:
    start_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
  base_controllers_switch:
    start_controllers:
      - controllers/chassis_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
  calibration_manager:
    trigger:
      switch:
        start_controllers:
          - controllers/trigger_calibration_controller
        stop_controllers:
          - controllers/shooter_controller
      query:
        service_name: /controllers/trigger_calibration_controller/is_calibrated
