rm_fsm:
  robot_type: "sentry"
  control_param:
    accel_x: 2.0
    accel_y: 5.0
    accel_angular: 10.0
    brake_multiple: 2
    shoot_hz: 20
    shoot_speed: 30
    gimbal_error_limit: 1
    rc_param:
      coefficient_x: 1.0
      coefficient_y: 1.0
      coefficient_angular: 6.0
      coefficient_yaw: 1.0
      coefficient_pitch: 1.0
  power_limit:
    danger_surplus: 20.0
    roll_back_buffer: 55.0
    coeff: 0.3
    multiple: 15.0
  auto_move:
    chassis_speed: 1.6
    chassis_accel: 1.0
    pitch_speed: 1.0
    yaw_speed: 3.4
    start: 0.0
    end: 2.0
    collision_distance: 0.3
    calibration_speed: 0.15
    column: 1