rm_fsm:
  robot_type: "standard"
  control_param:
    rc_param:
      accel_x: 5.0
      accel_y: 5.0
      accel_angular: 5.0
      brake_multiple: 2
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 6.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
      shoot_hz: 5.0
    pc_param:
      accel_x: 5.0
      accel_y: 5.0
      accel_angular: 5.0
      brake_multiple: 2
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 6.0
      coefficient_yaw: 600.0
      coefficient_pitch: 600.0
      shoot_hz: 5.0
  power_limit:
    danger_surplus_: 28.0
    roll_back_buffer_: 55.0
    coeff: 0.03
    multiple: 7.5
