rm_fsm:
  robot_type: "standard"
  control_param:
    accel_x: 7.5
    accel_y: 7.5
    accel_angular: 7.5
    brake_multiple: 1
    expect_shoot_hz: 10
    safe_shoot_hz: 3
    safe_shoot_speed: 10.0
    gimbal_error_limit: 0.17
    max_vel: 0.8
    rc_param:
      coefficient_x: 3.5
      coefficient_y: 3.5
      coefficient_angular: 6.0
      coefficient_yaw: 12.56
      coefficient_pitch: 12.56
    pc_param:
      coefficient_x: 5.0
      coefficient_y: 5.0
      coefficient_angular: 1.0
      coefficient_yaw: 750.0
      coefficient_pitch: 750.0
      normal_critical_speed: 0.5
      burst_critical_speed: 1.0
      normal_angular: 3.0
      burst_angular: 6.0
      spin_sin_amplitude: 3.0
      spin_sin_frequency: 6.28
  power_limit:
    ff: 1.0
    safety_current: 7.5
    wheel_radius: 0.07625
    use_power_manager: false
    max_limit_50w: 4.00
    max_limit_60w: 4.60
    max_limit_70w: 6.00
    max_limit_80w: 7.00
    max_limit_100w: 8.00
    max_limit_120w: 9.00
    pid_buffer: { p: 0.021, i: 0.005, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true }
    pid_buffer_power_manager: { p: 10.0, i: 0.1, d: 0.05, i_max: 0.0, i_min: 0.0, antiwindup: true }


