rm_fsm:
  robot_type: "sentry"
  chassis:
    topic: "/controllers/chassis_controller/command"
    accel_x:
      - [ 30.0,999.0 ]
    accel_y:
      - [ 30.0,0.0 ]
    accel_z:
      - [ 30.0,0.0 ]
    safety_power: 30.0
    capacitor_threshold: 0.1
    charge_power: 20.0
    extra_power: 30.0
    burst_power: 200.0
    safety_distance: 0.5
  vel:
    topic: "/cmd_vel"
    max_linear_x:
      - [ 30.0,3.0 ]
    max_linear_y:
      - [ 30.0,0.0 ]
    max_angular_z:
      - [ 30.0,0.0 ]
  auto:
    auto_linear_vel: 1.0
    enable_random_reversal: false
    min_interval_time: 0.8
    max_interval_time: 1.5
  lower:
    gimbal:
      topic: "/controllers/lower_gimbal_controller/command"
      max_yaw_vel: 1.5
      max_pitch_vel: 1.0
      track_timeout: 0.5
      target_cost_function:
        k_pos: 1.0
        k_vel: 1.0
        k_hp: 1.0
        k_freq: 1.0
        timeout: 0.05
    shooter:
      topic: "/controllers/lower_shooter_controller/command"
      gimbal_error_limit: 0.05
      gimbal_error_tolerance: 0.15
      target_acceleration_tolerance: 1.0
      accleration_moving_average_num: 10
      speed_15m_per_speed: 14.0
      speed_30m_per_speed: 30.0
      heat_limit:
        low_shoot_frequency: 10
        high_shoot_frequency: 20
        burst_shoot_frequency: 20
        safe_shoot_frequency: 20
        heat_coeff: 8.0
        type: "ID1_17MM"
    auto: { pitch: [ 0.03, 0.75 ], yaw: [ -2.75, 1.2 ] }
  upper:
    gimbal:
      topic: "/controllers/upper_gimbal_controller/command"
      max_yaw_vel: 1.5
      max_pitch_vel: 1.0
      track_timeout: 0.5
      target_cost_function:
        k_pos: 1.0
        k_vel: 1.0
        k_hp: 1.0
        k_freq: 1.0
        timeout: 0.05
    shooter:
      topic: "/controllers/upper_shooter_controller/command"
      gimbal_error_limit: 0.05
      gimbal_error_tolerance: 0.15
      target_acceleration_tolerance: 1.0
      accleration_moving_average_num: 10
      speed_15m_per_speed: 14.0
      speed_30m_per_speed: 30.0
      heat_limit:
        low_shoot_frequency: 10
        high_shoot_frequency: 20
        burst_shoot_frequency: 20
        safe_shoot_frequency: 20
        heat_coeff: 8.0
        type: "ID1_17MM"
    auto: { pitch: [ -0.012, 0.46 ], yaw: [ -2.2, 2.1 ] }
  controllers_list:
    state_controllers:
      - controllers/robot_state_controller
      - controllers/joint_state_controller
    main_controllers:
      - controllers/chassis_controller
      - controllers/tof_radar_controller
      - controllers/lower_orientation_controller
      - controllers/lower_gimbal_controller
      - controllers/lower_shooter_controller
    calibration_controllers:
      - controllers/lower_trigger_calibration_controller
      - controllers/lower_pitch_calibration_controller
      - controllers/catapult_calibration_controller
      - controllers/lower_yaw_calibration_controller
  chassis_gimbal_calibration:
    - start_controllers:
        - controllers/catapult_calibration_controller
        - controllers/lower_pitch_calibration_controller
        - controllers/lower_yaw_calibration_controller
      stop_controllers:
        - controllers/chassis_controller
        - controllers/lower_gimbal_controller
      services_name:
        - /controllers/lower_pitch_calibration_controller/is_calibrated
        - /controllers/lower_yaw_calibration_controller/is_calibrated
        - /controllers/catapult_calibration_controller/is_calibrated
  shooter_calibration:
    - start_controllers:
        - controllers/lower_trigger_calibration_controller
      stop_controllers:
        - controllers/lower_shooter_controller
      services_name:
        - /controllers/lower_trigger_calibration_controller/is_calibrated
